sudo: false
language: python
python:
- "2.7"
- "3.4"
- "3.5"
services:
- postgresql
install: "pip install -r requirements-dev.txt"
before_script:
- psql -c 'create database testdb;' -U postgres
script: make test
notifications:
  irc:
    channels:
    - "irc.freenode.net#umap"
    on_success: change
    on_failure: always
  email: false
branches:
  only:
  - master
